---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cert-manager-certificate
spec:
  secretName: mongodb-tls
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: "*.mongodb-name-svc.cert-manager.svc.cluster.local"
  dnsNames:
  - "*.mongodb-name-svc.cert-manager.svc.cluster.local"
  - k8s-node01
  - k8s-node02
  - k8s-node03
